In [545]:
#Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data.
#read the data file
import pandas as pd 
import numpy as np
df = pd.read_csv("Laliga.csv",skiprows=[0]) #including skiprows so that the first row is not considered

for col in df:
  df[col] = df[col].replace('-', 0)  #using replace function to replace hypen with zeros
print(df)

    Pos                 Team  Seasons Points GamesPlayed GamesWon GamesDrawn  \
0     1          Real Madrid       86   4385        2762     1647        552
1     2            Barcelona       86   4262        2762     1581        573
2     3      Atletico Madrid       80   3442        2614     1241        598
3     4             Valencia       82   3386        2664     1187        616
4     5      Athletic Bilbao       86   3368        2762     1209        633
5     6              Sevilla       73   2819        2408      990        531
6     7             Espanyol       82   2792        2626      948        608
7     8        Real Sociedad       70   2573        2302      864        577
8     9             Zaragoza       58   2109        1986      698        522
9    10           Real Betis       51   1884        1728      606        440
10   11  Deportivo La Coruna       45   1814        1530      563        392
11   12           Celta Vigo       51   1789        1698      586        389
12   13           Valladolid       42   1471        1466      463        384
13   14     Racing Santander       44   1416        1428      453        336
14   15       Sporting Gijon       43   1389        1458      471        358
15   16              Osasuna       37   1351        1318      426        327
16   17               Malaga       36   1314        1255      390        330
17   18               Oviedo       38   1174        1192      408        292
18   19             Mallorca       27   1148         988      333        256
19   20           Las Palmas       33   1020        1096      367        242
20   21           Villarreal       17    970         646      266        172
21   22              Granada       23    667         742      218        175
22   23       Rayo Vallecano       17    662         652      189        148
23   24                Elche       21    606         678      203        180
24   25               Getafe       12    553         456      147        112
25   26             Hercules       20    538         628      184        149
26   27             Tenerife       13    510         494      155        128
27   28               Murcia       18    445         586      145        143
28   29               Alaves       12    421         380      125         81
29   30              Levante       11    416         402      113         95
..  ...                  ...      ...    ...         ...      ...        ...
31   32             Sabadell       14    353         426      129         95
32   33                Cadiz       12    343         448      104        127
33   34             Logrones        9    293         346       96         92
34   35            Castellon       11    285         334      103         79
35   36             Albacete        7    277         270       76         76
36   37              Almeria        6    242         228       62         56
37   38              Cordoba        9    230         282       82         63
38   39           Compostela        4    190         160       52         45
39   40           Recreativo        5    188         186       50         46
40   41            Burgos CF        6    168         204       59         50
41   42           Pontevedra        6    150         180       53         44
42   43             Numancia        4    148         152       37         37
43   44                Eibar        3    132         114       35         27
44   45               Arenas        7    107         130       43         21
45   46          Real Burgos        3     96         114       26         44
46   47            Gimnastic        4     91         116       34         16
47   48          Extremadura        2     83          80       20         23
48   49               Merida        2     81          80       19         24
49   50             Alcoyano        4     76         108       30         16
50   51                 Jaen        3     71          90       29         13
51   52           Real Union        4     56          72       21         14
52   53           AD Almeria        2     52          68       17         18
53   54               Europa        3     42          54       18          6
54   55               Lleida        2     40          68       13         14
55   56              Leganes        1     35          38        8         11
56   57                Xerez        1     34          38        8         10
57   58               Condal        1     22          30        7          8
58   59      Atletico Tetuan        1     19          30        7          5
59   60     Cultural Leonesa        1     14          30        5          4
60   61               Girona        1      0           0        0          0

   GamesLost GoalsFor GoalsAgainst Champion Runner-up Third Fourth Fifth  \
0        563     5947         3140       33        23     8      8     3
1        608     5900         3114       25        25    12     12     4
2        775     4534         3309       10         8    16      9     7
3        861     4398         3469        6         6    10     11    10
4        920     4631         3700        8         7    10      5     8
5        887     3680         3373        1         4     4      5    12
6       1070     3609         3889        0         0     4      5     2
7        861     3228         3230        2         3     2      5     4
8        766     2683         2847        0         1     4      5     4
9        682     2159         2492        1         0     2      3     4
10       575     2052         2188        1         5     4      1     0
11       723     2278         2624        0         0     0      2     4
12       619     1767         2180        0         0     0      1     1
13       639     1843         2368        0         1     1      2     0
14       629     1753         2152        0         1     1      2     2
15       565     1500         1834        0         0     0      2     2
16       535     1421         1763        0         0     0      1     0
17       492     1642         1951        0         0     3      2     2
18       399     1182         1371        0         0     2      0     2
19       487     1347         1746        0         1     1      1     1
20       208      892          789        0         1     1      2     3
21       349      819         1157        0         0     0      0     0
22       305      760         1088        0         0     0      0     0
23       295      750         1022        0         0     0      0     1
24       197      520          633        0         0     0      0     0
25       295      716         1050        0         0     0      0     1
26       211      619          744        0         0     0      0     2
27       298      607          992        0         0     0      0     0
28       174      458          623        0         0     0      0     0
29       194      430          632        0         0     0      0     0
..       ...      ...          ...      ...       ...   ...    ...   ...
31       202      492          720        0         0     0      1     1
32       217      393          662        0         0     0      0     0
33       158      291          489        0         0     0      0     0
34       152      419          588        0         0     0      1     2
35       118      320          410        0         0     0      0     0
36       110      244          366        0         0     0      0     0
37       137      285          430        0         0     0      0     1
38        63      199          241        0         0     0      0     0
39        90      202          296        0         0     0      0     0
40        95      216          310        0         0     0      0     0
41        83      165          221        0         0     0      0     0
42        78      155          253        0         0     0      0     0
43        52      139          167        0         0     0      0     0
44        66      227          308        0         0     1      0     3
45        44      101          139        0         0     0      0     0
46        66      181          295        0         0     0      0     0
47        37       62          117        0         0     0      0     0
48        37       70          115        0         0     0      0     0
49        62      145          252        0         0     0      0     0
50        48      121          183        0         0     0      0     0
51        37      153          184        0         0     0      0     0
52        33       71          116        0         0     0      0     0
53        30       97          131        0         0     0      0     0
54        41       70          182        0         0     0      0     0
55        19       36           55        0         0     0      0     0
56        20       38           66        0         0     0      0     0
57        15       37           57        0         0     0      0     0
58        18       51           85        0         0     0      0     0
59        21       34           65        0         0     0      0     0
60         0        0            0        0         0     0      0     0

   Sixth   T    Debut Since/LastApp  BestPosition
0      4  79     1929          1929             1
1      6  83     1929          1929             1
2      6  56     1929       2002-03             1
3      7  50  1931-32       1987-88             1
4     10  49     1929          1929             1
5      6  32  1934-35       2001-02             1
6      5  16     1929       1994-95             3
7      3  19     1929       2010-11             1
8      4  18  1939-40       2012-13             2
9      4  14  1932-33       2015-16             1
10     1  12  1941-42       2014-15             1
11     5  11  1939-40       2012-13             4
12     1   3  1948-49       2013-14             4
13     1   5     1929       2011-12             2
14     1   7  1944-45       2015-16             2
15     2   6  1935-36       2016-17             4
16     1   2  1949-50       2008-09             4
17     4  11  1933-34       2000-01             3
18     1   5  1960-61       2012-13             3
19     1   5  1951-52       2015-16             2
20     2   9  1998-99       2013-14             2
21     2   2  1941-42       2016-17             6
22     0   0  1977-78       2015-16             8
23     1   2  1959-60       2014-15             5
24     1   1  2004-05       2015-16             6
25     4   5  1935-36       2010-11             5
26     0   2  1961-62       2009-10             5
27     0   0  1940-41       2007-08            11
28     1   1  1930-31       2016-17             6
29     1   1  1963-64       2015-16             6
..   ...  ..      ...           ...           ...
31     0   2  1943-44       1987-88             4
32     0   0  1977-78       2005-06            12
33     0   0  1987-88       1996-97             7
34     0   3  1941-42       1990-91             4
35     0   0  1991-92       2004-05             7
36     0   0  2007-08       2014-15             8
37     0   1  1962-63       2014-15             5
38     0   0  1994-95       1997-98            10
39     0   0  1978-79       2008-09             8
40     0   0  1971-72       1979-80            12
41     0   0  1963-64       1969-70             7
42     0   0  1999-00       2008-09            17
43     0   0  2014-15       2014-15            10
44     0   4     1929       1934-35             3
45     0   0  1990-91       1992-93             9
46     0   0  1947-48       2006-07             7
47     0   0  1996-97       1998-99            17
48     0   0  1995-96       1997-98            19
49     0   0  1945-46       1950-51            10
50     0   0  1953-54       1957-58            14
51     1   1     1929       1931-32             6
52     0   0  1979-80       1980-81            10
53     0   0     1929       1930-31             8
54     0   0  1950-51       1993-94            16
55     0   0  2016-17       2016-17            17
56     0   0  2009-10       2009-10            20
57     0   0  1956-57       1956-57            16
58     0   0  1951-52       1951-52            16
59     0   0  1955-56       1955-56            15
60     0   0  2017-18       2017-18             9

[61 rows x 20 columns]

In [754]:
#Print all the teams which have started playing between 1930-1980.
 #spliting the string on "-" and displays the starting string till hypen is encountered and comparing between 1930 and 1980
df_deb = df[(pd.to_numeric(df["Debut"].str.split("-").str[0]) >= 1930) & (pd.to_numeric(df["Debut"].str.split("-").str[0]) <= 1980)]  
print(df_deb.loc[:,["Team","Debut"]])

                   Team    Debut
3              Valencia  1931-32
5               Sevilla  1934-35
8              Zaragoza  1939-40
9            Real Betis  1932-33
10  Deportivo La Coruna  1941-42
11           Celta Vigo  1939-40
12           Valladolid  1948-49
14       Sporting Gijon  1944-45
15              Osasuna  1935-36
16               Malaga  1949-50
17               Oviedo  1933-34
18             Mallorca  1960-61
19           Las Palmas  1951-52
21              Granada  1941-42
22       Rayo Vallecano  1977-78
23                Elche  1959-60
25             Hercules  1935-36
26             Tenerife  1961-62
27               Murcia  1940-41
28               Alaves  1930-31
29              Levante  1963-64
30            Salamanca  1974-75
31             Sabadell  1943-44
32                Cadiz  1977-78
34            Castellon  1941-42
37              Cordoba  1962-63
39           Recreativo  1978-79
40            Burgos CF  1971-72
41           Pontevedra  1963-64
46            Gimnastic  1947-48
49             Alcoyano  1945-46
50                 Jaen  1953-54
52           AD Almeria  1979-80
54               Lleida  1950-51
57               Condal  1956-57
58      Atletico Tetuan  1951-52
59     Cultural Leonesa  1955-56

In [539]:
#Print the list of teams which came Top 5 in terms of points
df["Points"] = pd.to_numeric(df["Points"]) #converting to numeric as comparsion operation cannot be used on strings
df_sort=df.sort_values(by=["Points"],ascending=False).head(5)  # using Sort_values
print(df_sort.loc[:,["Team","Points"]])

              Team  Points
0      Real Madrid    4385
1        Barcelona    4262
2  Atletico Madrid    3442
3         Valencia    3386
4  Athletic Bilbao    3368

In [707]:
#Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. 
#Using the same function, find the team which has maximum and minimum goal difference

def Goal_diff_count(cols) :
    df_new = cols['Team'] ,  (pd.to_numeric(cols["GoalsFor"]) -  pd.to_numeric(cols['GoalsAgainst']))
    return pd.Series(df_new)

#finding the max difference by using apply to call the function Goal_diff_count and sort values 
print(df.apply(Goal_diff_count, axis=1).sort_values(by=[1],ascending=False).head(1))  # finding the max difference

#finding the min difference by using apply to call the function Goal_diff_count and sort values 
print(df.apply(Goal_diff_count, axis=1).sort_values(by=[1],ascending=True).head(1))  # finding the max difference

             0     1
0  Real Madrid  2807
                   0    1
13  Racing Santander -525

In [672]:
#Create a new column with name “Winning Percent” and append it to the data set
#Percentage of Winning = (GamesWon / GamesPlayed)*100
#If there are any numerical error, replace it with 0%
#Print the top 5 teams which has the highest Winning percentage

#Creating a new Column and replacing numerical error with 0 using fill na
df["WinningPercent"] = ((pd.to_numeric(df["GamesWon"]) / pd.to_numeric(df["GamesPlayed"]))*100).fillna(0).astype(int)
print(df)  # shows the new column WinningPercent appended to the last of the series and fillna is used to replace NaN with 0

    Pos                 Team  Seasons Points GamesPlayed GamesWon GamesDrawn  \
0     1          Real Madrid       86   4385        2762     1647        552
1     2            Barcelona       86   4262        2762     1581        573
2     3      Atletico Madrid       80   3442        2614     1241        598
3     4             Valencia       82   3386        2664     1187        616
4     5      Athletic Bilbao       86   3368        2762     1209        633
5     6              Sevilla       73   2819        2408      990        531
6     7             Espanyol       82   2792        2626      948        608
7     8        Real Sociedad       70   2573        2302      864        577
8     9             Zaragoza       58   2109        1986      698        522
9    10           Real Betis       51   1884        1728      606        440
10   11  Deportivo La Coruna       45   1814        1530      563        392
11   12           Celta Vigo       51   1789        1698      586        389
12   13           Valladolid       42   1471        1466      463        384
13   14     Racing Santander       44   1416        1428      453        336
14   15       Sporting Gijon       43   1389        1458      471        358
15   16              Osasuna       37   1351        1318      426        327
16   17               Malaga       36   1314        1255      390        330
17   18               Oviedo       38   1174        1192      408        292
18   19             Mallorca       27   1148         988      333        256
19   20           Las Palmas       33   1020        1096      367        242
20   21           Villarreal       17    970         646      266        172
21   22              Granada       23    667         742      218        175
22   23       Rayo Vallecano       17    662         652      189        148
23   24                Elche       21    606         678      203        180
24   25               Getafe       12    553         456      147        112
25   26             Hercules       20    538         628      184        149
26   27             Tenerife       13    510         494      155        128
27   28               Murcia       18    445         586      145        143
28   29               Alaves       12    421         380      125         81
29   30              Levante       11    416         402      113         95
..  ...                  ...      ...    ...         ...      ...        ...
31   32             Sabadell       14    353         426      129         95
32   33                Cadiz       12    343         448      104        127
33   34             Logrones        9    293         346       96         92
34   35            Castellon       11    285         334      103         79
35   36             Albacete        7    277         270       76         76
36   37              Almeria        6    242         228       62         56
37   38              Cordoba        9    230         282       82         63
38   39           Compostela        4    190         160       52         45
39   40           Recreativo        5    188         186       50         46
40   41            Burgos CF        6    168         204       59         50
41   42           Pontevedra        6    150         180       53         44
42   43             Numancia        4    148         152       37         37
43   44                Eibar        3    132         114       35         27
44   45               Arenas        7    107         130       43         21
45   46          Real Burgos        3     96         114       26         44
46   47            Gimnastic        4     91         116       34         16
47   48          Extremadura        2     83          80       20         23
48   49               Merida        2     81          80       19         24
49   50             Alcoyano        4     76         108       30         16
50   51                 Jaen        3     71          90       29         13
51   52           Real Union        4     56          72       21         14
52   53           AD Almeria        2     52          68       17         18
53   54               Europa        3     42          54       18          6
54   55               Lleida        2     40          68       13         14
55   56              Leganes        1     35          38        8         11
56   57                Xerez        1     34          38        8         10
57   58               Condal        1     22          30        7          8
58   59      Atletico Tetuan        1     19          30        7          5
59   60     Cultural Leonesa        1     14          30        5          4
60   61               Girona        1      0           0        0          0

   GamesLost GoalsFor GoalsAgainst       ...       Runner-up Third Fourth  \
0        563     5947         3140       ...              23     8      8
1        608     5900         3114       ...              25    12     12
2        775     4534         3309       ...               8    16      9
3        861     4398         3469       ...               6    10     11
4        920     4631         3700       ...               7    10      5
5        887     3680         3373       ...               4     4      5
6       1070     3609         3889       ...               0     4      5
7        861     3228         3230       ...               3     2      5
8        766     2683         2847       ...               1     4      5
9        682     2159         2492       ...               0     2      3
10       575     2052         2188       ...               5     4      1
11       723     2278         2624       ...               0     0      2
12       619     1767         2180       ...               0     0      1
13       639     1843         2368       ...               1     1      2
14       629     1753         2152       ...               1     1      2
15       565     1500         1834       ...               0     0      2
16       535     1421         1763       ...               0     0      1
17       492     1642         1951       ...               0     3      2
18       399     1182         1371       ...               0     2      0
19       487     1347         1746       ...               1     1      1
20       208      892          789       ...               1     1      2
21       349      819         1157       ...               0     0      0
22       305      760         1088       ...               0     0      0
23       295      750         1022       ...               0     0      0
24       197      520          633       ...               0     0      0
25       295      716         1050       ...               0     0      0
26       211      619          744       ...               0     0      0
27       298      607          992       ...               0     0      0
28       174      458          623       ...               0     0      0
29       194      430          632       ...               0     0      0
..       ...      ...          ...       ...             ...   ...    ...
31       202      492          720       ...               0     0      1
32       217      393          662       ...               0     0      0
33       158      291          489       ...               0     0      0
34       152      419          588       ...               0     0      1
35       118      320          410       ...               0     0      0
36       110      244          366       ...               0     0      0
37       137      285          430       ...               0     0      0
38        63      199          241       ...               0     0      0
39        90      202          296       ...               0     0      0
40        95      216          310       ...               0     0      0
41        83      165          221       ...               0     0      0
42        78      155          253       ...               0     0      0
43        52      139          167       ...               0     0      0
44        66      227          308       ...               0     1      0
45        44      101          139       ...               0     0      0
46        66      181          295       ...               0     0      0
47        37       62          117       ...               0     0      0
48        37       70          115       ...               0     0      0
49        62      145          252       ...               0     0      0
50        48      121          183       ...               0     0      0
51        37      153          184       ...               0     0      0
52        33       71          116       ...               0     0      0
53        30       97          131       ...               0     0      0
54        41       70          182       ...               0     0      0
55        19       36           55       ...               0     0      0
56        20       38           66       ...               0     0      0
57        15       37           57       ...               0     0      0
58        18       51           85       ...               0     0      0
59        21       34           65       ...               0     0      0
60         0        0            0       ...               0     0      0

   Fifth Sixth   T    Debut Since/LastApp BestPosition  WinningPercent
0      3     4  79     1929          1929            1              59
1      4     6  83     1929          1929            1              57
2      7     6  56     1929       2002-03            1              47
3     10     7  50  1931-32       1987-88            1              44
4      8    10  49     1929          1929            1              43
5     12     6  32  1934-35       2001-02            1              41
6      2     5  16     1929       1994-95            3              36
7      4     3  19     1929       2010-11            1              37
8      4     4  18  1939-40       2012-13            2              35
9      4     4  14  1932-33       2015-16            1              35
10     0     1  12  1941-42       2014-15            1              36
11     4     5  11  1939-40       2012-13            4              34
12     1     1   3  1948-49       2013-14            4              31
13     0     1   5     1929       2011-12            2              31
14     2     1   7  1944-45       2015-16            2              32
15     2     2   6  1935-36       2016-17            4              32
16     0     1   2  1949-50       2008-09            4              31
17     2     4  11  1933-34       2000-01            3              34
18     2     1   5  1960-61       2012-13            3              33
19     1     1   5  1951-52       2015-16            2              33
20     3     2   9  1998-99       2013-14            2              41
21     0     2   2  1941-42       2016-17            6              29
22     0     0   0  1977-78       2015-16            8              28
23     1     1   2  1959-60       2014-15            5              29
24     0     1   1  2004-05       2015-16            6              32
25     1     4   5  1935-36       2010-11            5              29
26     2     0   2  1961-62       2009-10            5              31
27     0     0   0  1940-41       2007-08           11              24
28     0     1   1  1930-31       2016-17            6              32
29     0     1   1  1963-64       2015-16            6              28
..   ...   ...  ..      ...           ...          ...             ...
31     1     0   2  1943-44       1987-88            4              30
32     0     0   0  1977-78       2005-06           12              23
33     0     0   0  1987-88       1996-97            7              27
34     2     0   3  1941-42       1990-91            4              30
35     0     0   0  1991-92       2004-05            7              28
36     0     0   0  2007-08       2014-15            8              27
37     1     0   1  1962-63       2014-15            5              29
38     0     0   0  1994-95       1997-98           10              32
39     0     0   0  1978-79       2008-09            8              26
40     0     0   0  1971-72       1979-80           12              28
41     0     0   0  1963-64       1969-70            7              29
42     0     0   0  1999-00       2008-09           17              24
43     0     0   0  2014-15       2014-15           10              30
44     3     0   4     1929       1934-35            3              33
45     0     0   0  1990-91       1992-93            9              22
46     0     0   0  1947-48       2006-07            7              29
47     0     0   0  1996-97       1998-99           17              25
48     0     0   0  1995-96       1997-98           19              23
49     0     0   0  1945-46       1950-51           10              27
50     0     0   0  1953-54       1957-58           14              32
51     0     1   1     1929       1931-32            6              29
52     0     0   0  1979-80       1980-81           10              25
53     0     0   0     1929       1930-31            8              33
54     0     0   0  1950-51       1993-94           16              19
55     0     0   0  2016-17       2016-17           17              21
56     0     0   0  2009-10       2009-10           20              21
57     0     0   0  1956-57       1956-57           16              23
58     0     0   0  1951-52       1951-52           16              23
59     0     0   0  1955-56       1955-56           15              16
60     0     0   0  2017-18       2017-18            9               0

[61 rows x 21 columns]

In [706]:
#printing the top 5 teams
df.sort_values(['WinningPercent'],ascending=False).head(5).groupby('WinningPercent')["WinningPercent","Team"].head(5)

   WinningPercent             Team
0              59      Real Madrid
1              57        Barcelona
2              47  Atletico Madrid
3              44         Valencia
4              43  Athletic Bilbao

In [761]:
#Group teams based on their “Best position” and print the sum of their points for all positions (10 points)
df["Points"] = pd.to_numeric(df["Points"])
df.groupby(["BestPosition"]).agg({"Points":["sum"]})

             Points
                sum
BestPosition
1             27933
2              6904
3              5221
4              6563
5              1884
6              2113
7              1186
8              1134
9                96
10              450
11              445
12              511
14               71
15               14
16               81
17              266
19               81
20               34